version: '2'
services:      
    mysql:
        container_name: mysql
        image: mysql
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        expose:
        - '3306'
   
    phpmyadmin:
        image: phpmyadmin
        depends_on:
            - "mysql"
        links:
            - "mysql"
        ports:
            - 8080:80  
        environment: 
            PMA_HOST: 'mysql'
            PMA_USER: 'root'
            PMA_PASSWORD: 'password'

    laravel:
        container_name: laravel
        build:
            context: builds/php-custom
        restart: always
        command: php artisan serve --host 0.0.0.0
        depends_on:
            - mysql
        ports:
            - 8000:8000
        environment: 
            docker: 'true'
            MYSQL_HOST: "mysql"
            MYSQL_DATABASE: "laravel"
            MYSQL_USER: "root"
            MYSQL_ROOT_PASSWORD: "password"
        volumes:
            - '.:/var/www/html'
        # networks:
        #     - sail
        # depends_on:
        #     - mysql

    react:
        container_name: react
        build:
            context: builds/node-custom
        command: npm start
        restart: always
        ports:
            - 3000:3000
        volumes:
            - ../../source/react/app:/app



